version: '2'
services:
    saos-swagger:
        container_name: saos-server
        restart: 'always'
        build:
            context: .
            dockerfile: Dockerfile
        image: saos-server:latest
        environment:
            - API_KEY=${API_KEY}
        ports:
            - 8080:8080
